### ISSUE TITLE
Repo doesn't work

### ISSUE THREAD

**Issue by dajpes** [antfu/vite-starter-ref-sugar#1]
Hi, 

I just tried using this repo using git clone, npm install and npm run dev but I got an error saying "count is undefined" :

![image](https://user-images.githubusercontent.com/11248816/98161318-884f3580-1ead-11eb-9987-a84a324e2cfa.png)

**Comment by antfu** [comment]
Tried `yarn`?

**Comment by dajpes** [comment]
Now it works using yarn, thank you man

**Comment by antfu** [comment]
I will update the readme addressing that. Thanks.
